-- ERM Navigator — base schema
-- Migrated from server.ts:15-129 (SQLite → Postgres).
-- Changes: AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY,
--          DATETIME DEFAULT CURRENT_TIMESTAMP → TIMESTAMPTZ DEFAULT NOW(),
--          quoted identifiers for camelCase columns (Postgres lowercases otherwise).

CREATE TABLE IF NOT EXISTS business_units (
  id TEXT PRIMARY KEY,
  name TEXT,
  industry TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE,
  password TEXT
);

CREATE TABLE IF NOT EXISTS pillars (
  id TEXT PRIMARY KEY,
  name TEXT
);

CREATE TABLE IF NOT EXISTS dimensions (
  id TEXT PRIMARY KEY,
  name TEXT
);

CREATE TABLE IF NOT EXISTS questions (
  id INTEGER PRIMARY KEY,
  text TEXT,
  "pillarId" TEXT REFERENCES pillars(id),
  "dimensionId" TEXT REFERENCES dimensions(id),
  "maxScore" INTEGER DEFAULT 5,
  weight REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS weights (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pillarId" TEXT,
  "dimensionId" TEXT,
  weight REAL
);

CREATE TABLE IF NOT EXISTS assessments (
  id TEXT PRIMARY KEY,
  "entityId" TEXT,
  "createdAt" TEXT,
  status TEXT DEFAULT 'draft',
  "overallScore" REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS responses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessmentId" TEXT REFERENCES assessments(id),
  "questionId" INTEGER REFERENCES questions(id),
  score REAL,
  "weightedScore" REAL,
  note TEXT DEFAULT '',
  "evidenceName" TEXT DEFAULT '',
  "answeredAt" TEXT DEFAULT '',
  UNIQUE("assessmentId", "questionId")
);

CREATE TABLE IF NOT EXISTS maturity_vectors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessmentId" TEXT REFERENCES assessments(id),
  "pillarId" TEXT,
  "dimensionId" TEXT,
  "weightedScore" REAL,
  "pillarScore" REAL,
  UNIQUE("assessmentId", "pillarId", "dimensionId")
);

CREATE TABLE IF NOT EXISTS benchmarks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT,
  "pillarId" TEXT,
  "dimensionId" TEXT,
  score REAL
);

CREATE TABLE IF NOT EXISTS drift_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessmentId" TEXT REFERENCES assessments(id),
  "entityId" TEXT REFERENCES business_units(id),
  "pillarId" TEXT,
  "deltaScore" REAL,
  "createdAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roadmap_actions (
  id TEXT PRIMARY KEY,
  "pillarId" TEXT,
  "dimensionId" TEXT,
  description TEXT,
  "expectedUplift" REAL,
  "costScore" INTEGER,
  "durationScore" INTEGER
);

CREATE TABLE IF NOT EXISTS roadmap_for_assessment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessmentId" TEXT REFERENCES assessments(id),
  "actionId" TEXT REFERENCES roadmap_actions(id),
  "priorityScore" REAL,
  phase TEXT
);

-- Indexes that keep the scoring + drift engines fast once data grows.
CREATE INDEX IF NOT EXISTS idx_questions_pillar_dim ON questions("pillarId", "dimensionId");
CREATE INDEX IF NOT EXISTS idx_responses_assessment ON responses("assessmentId");
CREATE INDEX IF NOT EXISTS idx_maturity_vectors_assessment ON maturity_vectors("assessmentId");
CREATE INDEX IF NOT EXISTS idx_assessments_entity ON assessments("entityId", status);
CREATE INDEX IF NOT EXISTS idx_drift_records_assessment ON drift_records("assessmentId");
CREATE INDEX IF NOT EXISTS idx_roadmap_assessment ON roadmap_for_assessment("assessmentId");
