-- ERM Navigator — minimal schema.
-- Only tables that hold genuinely user-generated state. All reference data
-- (pillars, dimensions, questions, weights, benchmarks, roadmap actions) is
-- bundled into the frontend (src/data/static.ts) and backend
-- (api/_lib/static.ts) as constants — no DB JOINs, no seed migrations.

CREATE TABLE IF NOT EXISTS assessments (
  id          TEXT PRIMARY KEY,
  "entityId"  TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status      TEXT NOT NULL DEFAULT 'completed'
);

CREATE TABLE IF NOT EXISTS responses (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessmentId" TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
  "questionId"   INTEGER NOT NULL,
  score          REAL NOT NULL,
  note           TEXT NOT NULL DEFAULT '',
  "evidenceName" TEXT NOT NULL DEFAULT '',
  "answeredAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE ("assessmentId", "questionId")
);

CREATE INDEX IF NOT EXISTS idx_assessments_entity_created ON assessments ("entityId", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_responses_assessment ON responses ("assessmentId");
